apiVersion: v1
kind: Service
metadata:
  labels:
    name: petclinic
  name: petclinic
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: harbor.tanzuworld.com/openso/petclinic:latest
        ports:
        - containerPort: 8080
